
variables:
    BASE_DISTROS: 'threat-rolling'  # 'threat-rolling threat-dev threat-last-snapshot'
    EXTRA_DISTROS: 'threat-experimental'  # 'threat-experimental threat-bleeding-edge'
    ARCHS: 'arm64'  # 'amd64 arm64 armhf'

stages:
    - build
    - register
    - test
    - push

build-rootfs:
    stage: build
    image: debian:unstable
    artifacts:
        paths:
            - "*.tar.xz"
            - "*.release.version"
    script: |
        set -e
        # Install tools
        apt-get -y update
        apt-get -y full-upgrade
        apt-get -y install debootstrap pixz qemu-user-static wget   kmod
        # Install Threat archive keyring
        KEYRING_PKG_URL=$(wget -nv -O - \
            https://threatcode.github.io/threat/dists/threat-rolling/main/binary-amd64/Packages.gz \
            | gzip -dc | grep ^Filename: | grep threat-archive-keyring | head -n 1 | awk '{print $2}')
        KEYRING_PKG_URL="https://threatcode.github.io/threat/$KEYRING_PKG_URL"
        wget -nv "$KEYRING_PKG_URL"
        dpkg -i threat-archive-keyring_*_all.deb
        rm threat-archive-keyring_*_all.deb
        # Enable support for additional executable binary formats
        update-binfmts --enable
        echo "Executable binary formats:"
        #update-binfmts --display | grep -v = | sed -e 's/^/  /' -e 's/:$//'
        update-binfmts --display
        # Debug
        echo "== ls -l /dev"
        ls -l /dev
        echo "== lsmod"
        lsmod
        echo "== cat /proc/mounts"
        cat /proc/mounts
        echo "== uname -a"
        uname -a
        echo "== cat /proc/cmdline"
        cat /proc/cmdline
        echo "== zgrep BINFMT_MISC /proc/config.gz"
        zgrep BINFMT_MISC /proc/config.gz
        # Test architectures right away
        echo "Arch test:"
        for arch in $ARCHS; do
            echo -n "* $arch: " && /usr/lib/arch-test/$arch
        done
        # Monkey patch debootstrap to properly detect docker
        if [ -z "$(. /usr/share/debootstrap/functions && detect_container && echo $CONTAINER)" ]; then
            echo "PATCHING DEBOOTSTRAP TO FIX DOCKER DETECTION cf. #985481"
            sed -E -i 's;(proc/1/mountinfo);\1 || [ -e /.dockerenv ];' /usr/share/debootstrap/functions
        fi
        # Since GitLab migrated to Google Container-Optimized OS & Docker 19.03.15
        # in August 2021, /builds is mounted with the option nodev, and it breaks
        # debootstrap. Workaround by using another location.
        # References:
        # * https://github.com/threatcode/build-scripts/threat-docker/-/issues/40
        # * https://gitlab.com/gitlab-com/gl-infra/production/-/issues/5184
        mkdir /work && cp build-rootfs.sh /work && cd /work
        # Build the various rootfs
        for distro in $BASE_DISTROS; do
            for arch in $ARCHS; do
                echo "========================================"
                echo "Building rootfs $distro/$arch"
                echo "========================================"
                ./build-rootfs.sh "$distro" "$arch"
            done
        done
        # Bring artifacts back in CI_PROJECT_DIR (see above)
        cp -v *.tar.xz *.release.version $CI_PROJECT_DIR

build-docker-images:
    stage: register
    image: docker:latest
    services:
        - docker:dind
    dependencies:
        - build-rootfs
    artifacts:
        paths:
            - "*.conf"
    script: |
        set -e
        apk update
        apk add bash
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        echo "$CI_JOB_TOKEN" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
        for distro in $BASE_DISTROS; do
            for arch in $ARCHS; do
                ./docker-build.sh "$distro" "$arch"
            done
        done
        for distro in $EXTRA_DISTROS; do
            for arch in $ARCHS; do
                ./docker-build-extra.sh "$distro" "$arch"
            done
        done

test-docker-images:
    stage: test
    image: docker:latest
    services:
        - docker:dind
    dependencies:
        - build-docker-images
    script: |
        set -e
        apk update
        apk add bash
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        for distro in $BASE_DISTROS $EXTRA_DISTROS; do
            for arch in $ARCHS; do
                ./docker-test.sh "$distro" "$arch"
            done
        done

push-docker-images:
    stage: push
    image: docker:latest
    services:
        - docker:dind
    dependencies:
        - build-docker-images
    script: |
        set -e
        apk update
        apk add bash
        echo "$CI_JOB_TOKEN" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
        if [ -n "$DOCKER_HUB_ACCESS_TOKEN" ]; then
            echo "$DOCKER_HUB_ACCESS_TOKEN" | docker login -u "$DOCKER_HUB_USER" --password-stdin "$DOCKER_HUB_REGISTRY"
        fi
        for distro in $BASE_DISTROS $EXTRA_DISTROS; do
            for arch in $ARCHS; do
                ./docker-push.sh "$distro" "$arch"
            done
        done
        for distro in $BASE_DISTROS $EXTRA_DISTROS; do
            ./docker-push-manifest.sh "$distro" "$ARCHS"
        done
        # Clean tags
        #apk add curl jq gawk
        #for distro in $BASE_DISTROS $EXTRA_DISTROS; do
        #    for arch in $ARCHS; do
        #        ./docker-cleanup.sh "$distro" "$arch"
        #    done
        #done
